/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Vocode from "../../../../api";
import * as core from "../../../../core";

export const UpdateNumberRequestExampleContext: core.serialization.Schema<
    serializers.UpdateNumberRequestExampleContext.Raw,
    Vocode.UpdateNumberRequestExampleContext
> = core.serialization.undiscriminatedUnion([
    core.serialization.record(core.serialization.string(), core.serialization.string()),
    core.serialization.lazyObject(async () => (await import("../../..")).Undefined),
]);

export declare namespace UpdateNumberRequestExampleContext {
    type Raw = Record<string, string> | serializers.Undefined.Raw;
}
