/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../..";

export interface UpdateVectorDatabaseRequest {
    id: string;
    body: Vocode.PineconeVectorDatabaseUpdateParams;
}
