/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Vocode from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.voices.listVoices.Response.Raw,
    Vocode.ListVoicesResponseItem[]
> = core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).ListVoicesResponseItem));

export declare namespace Response {
    type Raw = serializers.ListVoicesResponseItem.Raw[];
}
