/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../..";

export interface AgentParams {
    prompt: Vocode.AgentParamsPrompt;
    language?: Vocode.Language;
    actions?: Vocode.AgentParamsActionsItem[];
    voice: Vocode.AgentParamsVoice;
    initialMessage?: string;
    webhook?: Vocode.AgentParamsWebhook;
    vectorDatabase?: Vocode.AgentParamsVectorDatabase;
    interruptSensitivity?: Vocode.InterruptSensitivity;
    contextEndpoint?: string;
    noiseSuppression?: boolean;
    endpointingSensitivity?: Vocode.AgentParamsEndpointingSensitivity;
    ivrNavigationMode?: Vocode.AgentParamsIvrNavigationMode;
    conversationSpeed?: number;
    initialMessageDelay?: number;
    openaiModelNameOverride?: string;
    openaiAccountConnection?: Vocode.AgentParamsOpenaiAccountConnection;
    runDoNotCallDetection?: boolean;
}
