/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Vocode from "../../../../../api";
import * as core from "../../../../../core";

export const CreateCallRequest: core.serialization.Schema<serializers.CreateCallRequest.Raw, Vocode.CreateCallRequest> =
    core.serialization.object({
        fromNumber: core.serialization.property("from_number", core.serialization.string()),
        toNumber: core.serialization.property("to_number", core.serialization.string()),
        agent: core.serialization.lazy(async () => (await import("../../../..")).CreateCallRequestAgent),
        onNoHumanAnswer: core.serialization.property(
            "on_no_human_answer",
            core.serialization
                .lazy(async () => (await import("../../../..")).CreateCallRequestOnNoHumanAnswer)
                .optional()
        ),
        runDoNotCallDetection: core.serialization.property(
            "run_do_not_call_detection",
            core.serialization.boolean().optional()
        ),
        hipaaCompliant: core.serialization.property("hipaa_compliant", core.serialization.boolean().optional()),
        context: core.serialization.record(core.serialization.string(), core.serialization.string()).optional(),
    });

export declare namespace CreateCallRequest {
    interface Raw {
        from_number: string;
        to_number: string;
        agent: serializers.CreateCallRequestAgent.Raw;
        on_no_human_answer?: serializers.CreateCallRequestOnNoHumanAnswer.Raw | null;
        run_do_not_call_detection?: boolean | null;
        hipaa_compliant?: boolean | null;
        context?: Record<string, string> | null;
    }
}
