/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Vocode from "../../../../api";
import * as core from "../../../../core";

export const AgentParamsVectorDatabase: core.serialization.Schema<
    serializers.AgentParamsVectorDatabase.Raw,
    Vocode.AgentParamsVectorDatabase
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("../../..")).PineconeVectorDatabaseParams),
]);

export declare namespace AgentParamsVectorDatabase {
    type Raw = string | serializers.PineconeVectorDatabaseParams.Raw;
}
