/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type AccountConnectionUpdateParamsRequest =
    | Vocode.AccountConnectionUpdateParamsRequest.AccountConnectionTwilio
    | Vocode.AccountConnectionUpdateParamsRequest.AccountConnectionOpenai;

export declare namespace AccountConnectionUpdateParamsRequest {
    interface AccountConnectionTwilio extends Vocode.TwilioAccountConnectionUpdateParams {
        type: "account_connection_twilio";
    }

    interface AccountConnectionOpenai extends Vocode.OpenAiAccountConnectionUpdateParams {
        type: "account_connection_openai";
    }
}
