/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type AccountConnectionPageItemsItem =
    | Vocode.AccountConnectionPageItemsItem.AccountConnectionTwilio
    | Vocode.AccountConnectionPageItemsItem.AccountConnectionOpenai;

export declare namespace AccountConnectionPageItemsItem {
    interface AccountConnectionTwilio extends Vocode.TwilioAccountConnection {
        type: "account_connection_twilio";
    }

    interface AccountConnectionOpenai extends Vocode.OpenAiAccountConnection {
        type: "account_connection_openai";
    }
}
