/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type ActionType = "action_end_conversation" | "action_dtmf";

export const ActionType = {
    ActionEndConversation: "action_end_conversation",
    ActionDtmf: "action_dtmf",
} as const;
