/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type ActionUpdateParamsRequest =
    | Vocode.ActionUpdateParamsRequest.ActionTransferCall
    | Vocode.ActionUpdateParamsRequest.ActionEndConversation
    | Vocode.ActionUpdateParamsRequest.ActionDtmf;

export declare namespace ActionUpdateParamsRequest {
    interface ActionTransferCall extends Vocode.TransferCallActionUpdateParams {
        type: "action_transfer_call";
    }

    interface ActionEndConversation extends Vocode.EndConversationActionUpdateParams {
        type: "action_end_conversation";
    }

    interface ActionDtmf extends Vocode.DtmfActionUpdateParams {
        type: "action_dtmf";
    }
}
