/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface AddToConferenceActionParams {
    config: Vocode.AddToConferenceConfig;
    actionTrigger?: Vocode.AddToConferenceActionParamsActionTrigger;
}
