/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AgentIvrNavigationMode = "default" | "off";

export const AgentIvrNavigationMode = {
    Default: "default",
    Off: "off",
} as const;
