/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface Agent {
    id: string;
    userId: string;
    name?: string;
    prompt: Vocode.Prompt;
    language?: Vocode.Language;
    actions: Vocode.AgentActionsItem[];
    voice: Vocode.AgentVoice;
    initialMessage?: string;
    webhook?: Vocode.Webhook;
    vectorDatabase?: Vocode.PineconeVectorDatabase;
    interruptSensitivity?: Vocode.InterruptSensitivity;
    contextEndpoint?: string;
    noiseSuppression?: boolean;
    endpointingSensitivity?: Vocode.AgentEndpointingSensitivity;
    ivrNavigationMode?: Vocode.AgentIvrNavigationMode;
    conversationSpeed?: number;
    initialMessageDelay?: number;
    openaiModelNameOverride?: string;
    askIfHumanPresentOnIdle?: boolean;
    openaiAccountConnection?: Vocode.OpenAiAccountConnection;
    runDoNotCallDetection?: boolean;
    llmFallback?: Vocode.InternalLlmFallback;
    deepgramKeywords?: Record<string, Vocode.AgentDeepgramKeywordsValue | undefined>;
    idleTimeSeconds?: number;
    llmTemperature?: number;
}
