/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AgentUpdateParamsEndpointingSensitivity = "auto" | "relaxed";

export const AgentUpdateParamsEndpointingSensitivity = {
    Auto: "auto",
    Relaxed: "relaxed",
} as const;
