/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type AgentParamsActionsItem =
    | string
    | Vocode.TransferCallActionParams
    | Vocode.EndConversationActionParams
    | Vocode.DtmfActionParams;
