/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type AgentActionsItem = string | Vocode.TransferCallAction | Vocode.EndConversationAction | Vocode.DtmfAction;
