/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type AgentParamsActionsItemOne =
    | Vocode.AgentParamsActionsItemOne.ActionTransferCall
    | Vocode.AgentParamsActionsItemOne.ActionEndConversation
    | Vocode.AgentParamsActionsItemOne.ActionDtmf;

export declare namespace AgentParamsActionsItemOne {
    interface ActionTransferCall extends Vocode.TransferCallActionParams {
        type: "action_transfer_call";
    }

    interface ActionEndConversation extends Vocode.EndConversationActionParams {
        type: "action_end_conversation";
    }

    interface ActionDtmf extends Vocode.DtmfActionParams {
        type: "action_dtmf";
    }
}
