/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AgentParamsEndpointingSensitivity = "auto" | "relaxed";

export const AgentParamsEndpointingSensitivity = {
    Auto: "auto",
    Relaxed: "relaxed",
} as const;
