/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type AgentUpdateParamsVoice =
    | string
    | Vocode.AzureVoiceUpdateParams
    | Vocode.RimeVoiceUpdateParams
    | Vocode.ElevenLabsVoiceUpdateParams
    | Vocode.PlayHtVoiceUpdateParams
    | Vocode.Undefined;
