/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type AgentUpdateParamsActionsItemOne =
    | Vocode.AgentUpdateParamsActionsItemOne.ActionTransferCall
    | Vocode.AgentUpdateParamsActionsItemOne.ActionEndConversation
    | Vocode.AgentUpdateParamsActionsItemOne.ActionDtmf
    | Vocode.AgentUpdateParamsActionsItemOne.ActionAddToConference
    | Vocode.AgentUpdateParamsActionsItemOne.ActionSetHold
    | Vocode.AgentUpdateParamsActionsItemOne.ActionExternal;

export declare namespace AgentUpdateParamsActionsItemOne {
    interface ActionTransferCall extends Vocode.TransferCallActionUpdateParams {
        type: "action_transfer_call";
    }

    interface ActionEndConversation extends Vocode.EndConversationActionUpdateParams {
        type: "action_end_conversation";
    }

    interface ActionDtmf extends Vocode.DtmfActionUpdateParams {
        type: "action_dtmf";
    }

    interface ActionAddToConference extends Vocode.AddToConferenceActionUpdateParams {
        type: "action_add_to_conference";
    }

    interface ActionSetHold extends Vocode.SetHoldActionUpdateParams {
        type: "action_set_hold";
    }

    interface ActionExternal extends Vocode.ExternalActionUpdateParams {
        type: "action_external";
    }
}
