/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type AgentUpdateParamsVoiceOne =
    | Vocode.AgentUpdateParamsVoiceOne.VoiceAzure
    | Vocode.AgentUpdateParamsVoiceOne.VoiceRime
    | Vocode.AgentUpdateParamsVoiceOne.VoiceElevenLabs
    | Vocode.AgentUpdateParamsVoiceOne.VoicePlayHt;

export declare namespace AgentUpdateParamsVoiceOne {
    interface VoiceAzure extends Vocode.AzureVoiceUpdateParams {
        type: "voice_azure";
    }

    interface VoiceRime extends Vocode.RimeVoiceUpdateParams {
        type: "voice_rime";
    }

    interface VoiceElevenLabs extends Vocode.ElevenLabsVoiceUpdateParams {
        type: "voice_eleven_labs";
    }

    interface VoicePlayHt extends Vocode.PlayHtVoiceUpdateParams {
        type: "voice_play_ht";
    }
}
