/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type AgentUpdateParamsActionsAgentUpdateParamsActionsItem =
    | string
    | Vocode.TransferCallActionUpdateParams
    | Vocode.EndConversationActionUpdateParams
    | Vocode.DtmfActionUpdateParams;
