/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface AgentUpdateParams {
    prompt?: Vocode.AgentUpdateParamsPrompt;
    actions?: Vocode.AgentUpdateParamsActions;
    voice?: Vocode.AgentUpdateParamsVoice;
    initialMessage?: Vocode.AgentUpdateParamsInitialMessage;
    webhook?: Vocode.AgentUpdateParamsWebhook;
}
