/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AgentEndpointingSensitivity = "auto" | "relaxed" | "sensitive";

export const AgentEndpointingSensitivity = {
    Auto: "auto",
    Relaxed: "relaxed",
    Sensitive: "sensitive",
} as const;
