/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type AgentUpdateParamsActions = Vocode.AgentUpdateParamsActionsItem[] | Vocode.Undefined;
