/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AgentEndpointingSensitivity = "auto" | "relaxed";

export const AgentEndpointingSensitivity = {
    Auto: "auto",
    Relaxed: "relaxed",
} as const;
