/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface AzureVoiceUpdateParams {
    voiceName?: Vocode.AzureVoiceUpdateParamsVoiceName;
    pitch?: Vocode.AzureVoiceUpdateParamsPitch;
    rate?: Vocode.AzureVoiceUpdateParamsRate;
}
