/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface AzureVoiceParams {
    type: Vocode.VoiceType;
    voiceName: string;
    pitch?: number;
    rate?: number;
}
