/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CallStageOutcome =
    | "human_unanswered"
    | "human_disconnected"
    | "bot_disconnected"
    | "transfer_unanswered"
    | "transfer_disconnected";

export const CallStageOutcome = {
    HumanUnanswered: "human_unanswered",
    HumanDisconnected: "human_disconnected",
    BotDisconnected: "bot_disconnected",
    TransferUnanswered: "transfer_unanswered",
    TransferDisconnected: "transfer_disconnected",
} as const;
