/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface CallPage {
    items: Vocode.NormalizedCall[];
    page: number;
    size: number;
    hasMore: boolean;
}
