/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CallMachineDetectionResult = "human" | "machine";

export const CallMachineDetectionResult = {
    Human: "human",
    Machine: "machine",
} as const;
