/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface Call {
    id: string;
    userId: string;
    toNumber: string;
    fromNumber: string;
    agent: Vocode.CallAgent;
    goal?: string;
    transcript?: string;
    recordingUrl?: string;
    status: Vocode.CallStatus;
    errorMessage?: string;
    recordingAvailable?: boolean;
}
