/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface Call {
    id: string;
    userId: string;
    status?: Vocode.CallStatus;
    errorMessage?: string;
    recordingAvailable?: boolean;
    transcript?: string;
    machineDetectionResult?: Vocode.CallMachineDetectionResult;
    toNumber: string;
    fromNumber: string;
    agent: Vocode.Agent;
    agentPhoneNumber: string;
    startTime?: Date;
    endTime?: Date;
}
