/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type CallStatus = "not_started" | "in_progress" | "error" | "ended";

export const CallStatus = {
    NotStarted: "not_started",
    InProgress: "in_progress",
    Error: "error",
    Ended: "ended",
} as const;
