/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CallTelephonyProvider = "vonage" | "twilio";

export const CallTelephonyProvider = {
    Vonage: "vonage",
    Twilio: "twilio",
} as const;
