/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CallOnNoHumanAnswer = "continue" | "hangup";

export const CallOnNoHumanAnswer = {
    Continue: "continue",
    Hangup: "hangup",
} as const;
