/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CollectField {
    fieldType: "field_type_email";
    label: string;
    name: string;
    description?: string;
}
