/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../index";

export interface CreateCallAgentParams {
    name?: string;
    prompt: Vocode.CreateCallAgentParamsPrompt;
    language?: Vocode.Language;
    actions?: Vocode.CreateCallAgentParamsActionsItem[];
    voice?: Vocode.CreateCallAgentParamsVoice;
    initialMessage?: string;
    webhook?: Vocode.CreateCallAgentParamsWebhook;
    vectorDatabase?: Vocode.CreateCallAgentParamsVectorDatabase;
    interruptSensitivity?: Vocode.InterruptSensitivity;
    contextEndpoint?: string;
    noiseSuppression?: boolean;
    endpointingSensitivity?: Vocode.CreateCallAgentParamsEndpointingSensitivity;
    ivrNavigationMode?: Vocode.CreateCallAgentParamsIvrNavigationMode;
    conversationSpeed?: number;
    initialMessageDelay?: number;
    openaiModelNameOverride?: string;
    askIfHumanPresentOnIdle?: boolean;
    openaiAccountConnection?: Vocode.CreateCallAgentParamsOpenaiAccountConnection;
    runDoNotCallDetection?: boolean;
    llmFallback?: Vocode.InternalLlmFallback;
    deepgramKeywords?: Record<string, Vocode.CreateCallAgentParamsDeepgramKeywordsValue | undefined>;
    idleTimeSeconds?: number;
    llmTemperature?: number;
}
