/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateCallAgentParamsIvrNavigationMode = "default" | "off";

export const CreateCallAgentParamsIvrNavigationMode = {
    Default: "default",
    Off: "off",
} as const;
