/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type CreateCallAgentParamsVoice =
    | string
    | Vocode.AzureVoiceParams
    | Vocode.RimeVoiceParams
    | Vocode.ElevenLabsVoiceParams
    | Vocode.PlayHtVoiceParams;
