/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CreateCallRequestOnMachineAnswer = "continue" | "hangup";

export const CreateCallRequestOnMachineAnswer = {
    Continue: "continue",
    Hangup: "hangup",
} as const;
