/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type ElevenLabsVoiceUpdateParamsExperimentalInputStreaming = boolean | Vocode.Undefined;
