/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ElevenLabsVoice {
    id: string;
    userId: string;
    voiceId: string;
    stability?: number;
    similarityBoost?: number;
    apiKey?: string;
    optimizeStreamingLatency?: number;
    modelId?: string;
    experimentalInputStreaming?: boolean;
}
