/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface ElevenLabsVoiceUpdateParams {
    type: Vocode.VoiceType;
    voiceId?: Vocode.ElevenLabsVoiceUpdateParamsVoiceId;
    stability?: Vocode.ElevenLabsVoiceUpdateParamsStability;
    similarityBoost?: Vocode.ElevenLabsVoiceUpdateParamsSimilarityBoost;
    apiKey?: Vocode.ElevenLabsVoiceUpdateParamsApiKey;
}
