/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface EndConversationActionParams {
    type: Vocode.ActionType;
    config?: Vocode.ActionConfig;
}
