/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type EventType =
    | "event_message"
    | "event_action"
    | "event_phone_call_connected"
    | "event_phone_call_ended"
    | "event_transcript"
    | "event_recording";

export const EventType = {
    EventMessage: "event_message",
    EventAction: "event_action",
    EventPhoneCallConnected: "event_phone_call_connected",
    EventPhoneCallEnded: "event_phone_call_ended",
    EventTranscript: "event_transcript",
    EventRecording: "event_recording",
} as const;
