/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface ExternalAction {
    id: string;
    userId: string;
    config: Vocode.ExternalActionConfig;
    actionTrigger?: Vocode.ExternalActionActionTrigger;
}
