/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface ExternalActionUpdateParams {
    config?: Vocode.ExternalActionUpdateParamsConfig;
    actionTrigger?: Vocode.ExternalActionUpdateParamsActionTrigger;
}
