/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type ExternalActionParamsActionTrigger =
    | Vocode.ExternalActionParamsActionTrigger.ActionTriggerFunctionCall
    | Vocode.ExternalActionParamsActionTrigger.ActionTriggerPhraseBased;

export declare namespace ExternalActionParamsActionTrigger {
    interface ActionTriggerFunctionCall extends Vocode.FunctionCallActionTrigger {
        type: "action_trigger_function_call";
    }

    interface ActionTriggerPhraseBased extends Vocode.PhraseBasedActionTrigger {
        type: "action_trigger_phrase_based";
    }
}
