/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ExternalActionConfig {
    processingMode?: "muted";
    name: string;
    description: string;
    url: string;
    inputSchema: Record<string, unknown>;
    speakOnSend: boolean;
    speakOnReceive: boolean;
}
