/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface ExternalActionParams {
    config: Vocode.ExternalActionConfig;
    actionTrigger?: Vocode.ExternalActionParamsActionTrigger;
}
