/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type InterruptSensitivity = "low" | "high";

export const InterruptSensitivity = {
    Low: "low",
    High: "high",
} as const;
