/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface NormalizedCall {
    id: string;
    userId: string;
    status?: Vocode.CallStatus;
    errorMessage?: string;
    recordingAvailable?: boolean;
    transcript?: string;
    humanDetectionResult?: Vocode.NormalizedCallHumanDetectionResult;
    doNotCallResult?: boolean;
    telephonyId?: string;
    stage?: Vocode.NormalizedCallStage;
    stageOutcome?: Vocode.NormalizedCallStageOutcome;
    toNumber: string;
    fromNumber: string;
    agent: string;
    telephonyProvider: Vocode.NormalizedCallTelephonyProvider;
    agentPhoneNumber: string;
    startTime?: Date;
    endTime?: Date;
    hipaaCompliant?: boolean;
    onNoHumanAnswer?: Vocode.NormalizedCallOnNoHumanAnswer;
    context?: Record<string, string>;
    runDoNotCallDetection?: boolean;
    telephonyAccountConnection?: Vocode.NormalizedCallTelephonyAccountConnection;
    telephonyParams?: Record<string, string>;
}
