/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NormalizedCallMachineDetectionResult = "human" | "machine";

export const NormalizedCallMachineDetectionResult = {
    Human: "human",
    Machine: "machine",
} as const;
