/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface NormalizedCall {
    id: string;
    userId: string;
    status?: Vocode.CallStatus;
    errorMessage?: string;
    recordingAvailable?: boolean;
    transcript?: string;
    machineDetectionResult?: Vocode.NormalizedCallMachineDetectionResult;
    toNumber: string;
    fromNumber: string;
    agent: string;
    agentPhoneNumber: string;
    startTime?: Date;
    endTime?: Date;
    hipaaCompliant?: boolean;
}
