/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NormalizedPhoneNumberTelephonyProvider = "vonage" | "twilio";

export const NormalizedPhoneNumberTelephonyProvider = {
    Vonage: "vonage",
    Twilio: "twilio",
} as const;
