/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NormalizedAgentEndpointingSensitivity = "auto" | "relaxed";

export const NormalizedAgentEndpointingSensitivity = {
    Auto: "auto",
    Relaxed: "relaxed",
} as const;
