/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type NormalizedCallTelephonyAccountConnection = string | Vocode.TwilioAccountConnection;
