/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type NormalizedCallTelephonyProvider = "vonage" | "twilio";

export const NormalizedCallTelephonyProvider = {
    Vonage: "vonage",
    Twilio: "twilio",
} as const;
