/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface NormalizedPhoneNumber {
    id: string;
    userId: string;
    active?: boolean;
    label?: string;
    inboundAgent: string;
    outboundOnly?: boolean;
    number: string;
}
