/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface NormalizedAgent {
    id: string;
    userId: string;
    prompt: string;
    language?: Vocode.Language;
    actions: string[];
    voice: string;
    initialMessage?: string;
    webhook?: string;
    vectorDatabase?: Vocode.NormalizedAgentVectorDatabase;
    interruptSensitivity?: Vocode.InterruptSensitivity;
    contextEndpoint?: string;
}
