/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface OpenAiAccountConnection {
    id: string;
    userId: string;
    type: "account_connection_openai";
    credentials: Vocode.OpenAiCredentials;
}
