/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface PhoneNumber {
    id: string;
    userId: string;
    number: string;
    active: boolean;
    inboundAgent: Vocode.PhoneNumberInboundAgent;
}
