/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PhoneNumberTelephonyProvider = "vonage" | "twilio";

export const PhoneNumberTelephonyProvider = {
    Vonage: "vonage",
    Twilio: "twilio",
} as const;
