/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface PhoneNumber {
    id: string;
    userId: string;
    active?: boolean;
    label?: string;
    inboundAgent: Vocode.Agent;
    outboundOnly?: boolean;
    exampleContext?: Record<string, string>;
    number: string;
    telephonyProvider?: Vocode.PhoneNumberTelephonyProvider;
    telephonyAccountConnection?: Vocode.TwilioAccountConnection;
}
