/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface PineconeVectorDatabaseUpdateParams {
    type: Vocode.VectorDatabaseType;
    index?: Vocode.PineconeVectorDatabaseUpdateParamsIndex;
    apiKey?: Vocode.PineconeVectorDatabaseUpdateParamsApiKey;
    apiEnvironment?: Vocode.PineconeVectorDatabaseUpdateParamsApiEnvironment;
}
