/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PineconeVectorDatabaseParams {
    type: "vector_database_pinecone";
    index: string;
    apiKey: string;
    apiEnvironment: string;
}
