/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface PineconeVectorDatabaseParams {
    type: Vocode.VectorDatabaseType;
    index: string;
    apiKey: string;
    apiEnvironment: string;
}
