/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type PlanType = "plan_free" | "plan_developer" | "plan_enterprise";

export const PlanType = {
    PlanFree: "plan_free",
    PlanDeveloper: "plan_developer",
    PlanEnterprise: "plan_enterprise",
} as const;
