/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface PlayHtVoice {
    id: string;
    userId: string;
    voiceId: string;
    apiUserId?: string;
    apiKey?: string;
    version?: Vocode.PlayHtVoiceVersion;
    speed?: number;
    quality?: Vocode.PlayHtVoiceQuality;
    temperature?: number;
    topP?: number;
    textGuidance?: number;
    voiceGuidance?: number;
    experimentalRemoveSilence?: boolean;
}
