/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PlayHtVoice {
    id: string;
    userId: string;
    voiceId: string;
    apiUserId: string;
    apiKey: string;
}
