/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PlayHtVoiceParamsQuality = "faster" | "draft" | "low" | "medium" | "high" | "premium";

export const PlayHtVoiceParamsQuality = {
    Faster: "faster",
    Draft: "draft",
    Low: "low",
    Medium: "medium",
    High: "high",
    Premium: "premium",
} as const;
