/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type PlayHtVoiceUpdateParamsQuality =
    | "faster"
    | "draft"
    | "low"
    | "medium"
    | "high"
    | "premium"
    | Vocode.Undefined;
