/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface Prompt {
    id: string;
    userId: string;
    content: string;
    collectFields?: Vocode.CollectField[];
    contextEndpoint?: string;
}
