/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface PromptUpdateParams {
    content?: Vocode.PromptUpdateParamsContent;
    collectFields?: Vocode.PromptUpdateParamsCollectFields;
    contextEndpoint?: Vocode.PromptUpdateParamsContextEndpoint;
}
