/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PromptTemplate {
    id: string;
    userId: string;
    label?: string;
    requiredContextKeys: string[];
}
