/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface RimeVoiceUpdateParams {
    type: Vocode.VoiceType;
    speaker?: Vocode.RimeVoiceUpdateParamsSpeaker;
}
