/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface SetHoldActionUpdateParams {
    config?: Vocode.SetHoldActionUpdateParamsConfig;
    actionTrigger?: Vocode.SetHoldActionUpdateParamsActionTrigger;
}
