/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type SetHoldActionParamsActionTrigger =
    | Vocode.SetHoldActionParamsActionTrigger.ActionTriggerFunctionCall
    | Vocode.SetHoldActionParamsActionTrigger.ActionTriggerPhraseBased;

export declare namespace SetHoldActionParamsActionTrigger {
    interface ActionTriggerFunctionCall extends Vocode.FunctionCallActionTrigger {
        type: "action_trigger_function_call";
    }

    interface ActionTriggerPhraseBased extends Vocode.PhraseBasedActionTrigger {
        type: "action_trigger_phrase_based";
    }
}
