/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface SetHoldAction {
    id: string;
    userId: string;
    config?: Vocode.EmptyActionConfig;
    actionTrigger?: Vocode.SetHoldActionActionTrigger;
}
