/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface TransferCallAction {
    id: string;
    userId: string;
    type?: Vocode.ActionType;
    config: Vocode.TransferCallConfig;
}
