/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface TransferCallActionUpdateParams {
    config?: Vocode.TransferCallActionUpdateParamsConfig;
    actionTrigger?: Vocode.TransferCallActionUpdateParamsActionTrigger;
}
