/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface TwilioAccountConnectionParams {
    credentials: Vocode.TwilioCredentials;
    steeringPool?: string[];
    accountSupportsAnyCallerId?: boolean;
}
