/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface TwilioAccountConnection {
    id: string;
    userId: string;
    type: "account_connection_twilio";
    credentials: Vocode.TwilioCredentials;
}
