/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export type UpdateVoiceResponse = Vocode.AzureVoice | Vocode.RimeVoice | Vocode.ElevenLabsVoice | Vocode.PlayHtVoice;
