/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface ValidationError {
    loc: Vocode.ValidationErrorLocItem[];
    msg: string;
    type: string;
}
