/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An enumeration.
 */
export type VoiceType = "voice_azure" | "voice_rime" | "voice_eleven_labs";

export const VoiceType = {
    VoiceAzure: "voice_azure",
    VoiceRime: "voice_rime",
    VoiceElevenLabs: "voice_eleven_labs",
} as const;
