/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface WebhookUpdateParams {
    subscriptions?: Vocode.WebhookUpdateParamsSubscriptions;
    url?: Vocode.WebhookUpdateParamsUrl;
    method?: Vocode.WebhookUpdateParamsMethod;
}
