/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "..";

export interface Webhook {
    id: string;
    userId: string;
    subscriptions: Vocode.EventType[];
    url: string;
    method?: Vocode.HttpMethod;
}
