/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../..";

export interface UpdateVoiceRequest {
    id: string;
    body: Vocode.VoiceUpdateParamsRequest;
}
