/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LinkPhoneNumberRequest {
    phoneNumber: string;
    telephonyAccountConnection: string;
    outboundOnly?: boolean;
}
