/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../..";

export interface UpdateNumberRequest {
    phoneNumber: string;
    inboundAgent: Vocode.UpdateNumberRequestInboundAgent;
}
