/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AccountConnectionPageItemsItem: core.serialization.Schema<
    serializers.AccountConnectionPageItemsItem.Raw,
    Vocode.AccountConnectionPageItemsItem
> = core.serialization
    .union("type", {
        account_connection_twilio: core.serialization.lazyObject(
            async () => (await import("..")).TwilioAccountConnection
        ),
        account_connection_openai: core.serialization.lazyObject(
            async () => (await import("..")).OpenAiAccountConnection
        ),
    })
    .transform<Vocode.AccountConnectionPageItemsItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace AccountConnectionPageItemsItem {
    type Raw =
        | AccountConnectionPageItemsItem.AccountConnectionTwilio
        | AccountConnectionPageItemsItem.AccountConnectionOpenai;

    interface AccountConnectionTwilio extends serializers.TwilioAccountConnection.Raw {
        type: "account_connection_twilio";
    }

    interface AccountConnectionOpenai extends serializers.OpenAiAccountConnection.Raw {
        type: "account_connection_openai";
    }
}
