/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AccountConnectionPage: core.serialization.ObjectSchema<
    serializers.AccountConnectionPage.Raw,
    Vocode.AccountConnectionPage
> = core.serialization.object({
    items: core.serialization.list(
        core.serialization.lazy(async () => (await import("..")).AccountConnectionPageItemsItem)
    ),
    page: core.serialization.number(),
    size: core.serialization.number(),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    total: core.serialization.number(),
    totalIsEstimated: core.serialization.property("total_is_estimated", core.serialization.boolean()),
});

export declare namespace AccountConnectionPage {
    interface Raw {
        items: serializers.AccountConnectionPageItemsItem.Raw[];
        page: number;
        size: number;
        has_more: boolean;
        total: number;
        total_is_estimated: boolean;
    }
}
