/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const ActionPageItemsItem: core.serialization.Schema<
    serializers.ActionPageItemsItem.Raw,
    Vocode.ActionPageItemsItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).TransferCallAction),
    core.serialization.lazyObject(async () => (await import("..")).EndConversationAction),
    core.serialization.lazyObject(async () => (await import("..")).DtmfAction),
]);

export declare namespace ActionPageItemsItem {
    type Raw = serializers.TransferCallAction.Raw | serializers.EndConversationAction.Raw | serializers.DtmfAction.Raw;
}
