/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const ActionConfig: core.serialization.ObjectSchema<serializers.ActionConfig.Raw, Vocode.ActionConfig> =
    core.serialization.object({});

export declare namespace ActionConfig {
    interface Raw {}
}
