/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AddToConferenceAction: core.serialization.ObjectSchema<
    serializers.AddToConferenceAction.Raw,
    Vocode.AddToConferenceAction
> = core.serialization.object({
    id: core.serialization.string(),
    userId: core.serialization.property("user_id", core.serialization.string()),
    config: core.serialization.lazyObject(async () => (await import("..")).AddToConferenceConfig),
    actionTrigger: core.serialization.property(
        "action_trigger",
        core.serialization.lazy(async () => (await import("..")).AddToConferenceActionActionTrigger).optional()
    ),
});

export declare namespace AddToConferenceAction {
    interface Raw {
        id: string;
        user_id: string;
        config: serializers.AddToConferenceConfig.Raw;
        action_trigger?: serializers.AddToConferenceActionActionTrigger.Raw | null;
    }
}
