/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AgentParamsActionsItem: core.serialization.Schema<
    serializers.AgentParamsActionsItem.Raw,
    Vocode.AgentParamsActionsItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("..")).TransferCallActionParams),
    core.serialization.lazyObject(async () => (await import("..")).EndConversationActionParams),
    core.serialization.lazyObject(async () => (await import("..")).DtmfActionParams),
]);

export declare namespace AgentParamsActionsItem {
    type Raw =
        | string
        | serializers.TransferCallActionParams.Raw
        | serializers.EndConversationActionParams.Raw
        | serializers.DtmfActionParams.Raw;
}
