/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AgentUpdateParams: core.serialization.ObjectSchema<
    serializers.AgentUpdateParams.Raw,
    Vocode.AgentUpdateParams
> = core.serialization.object({
    prompt: core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsPrompt).optional(),
    language: core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsLanguage).optional(),
    actions: core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsActions).optional(),
    voice: core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsVoice).optional(),
    initialMessage: core.serialization.property(
        "initial_message",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsInitialMessage).optional()
    ),
    webhook: core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsWebhook).optional(),
    vectorDatabase: core.serialization.property(
        "vector_database",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsVectorDatabase).optional()
    ),
    interruptSensitivity: core.serialization.property(
        "interrupt_sensitivity",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsInterruptSensitivity).optional()
    ),
    contextEndpoint: core.serialization.property(
        "context_endpoint",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsContextEndpoint).optional()
    ),
    noiseSuppression: core.serialization.property(
        "noise_suppression",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsNoiseSuppression).optional()
    ),
    endpointingSensitivity: core.serialization.property(
        "endpointing_sensitivity",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsEndpointingSensitivity).optional()
    ),
});

export declare namespace AgentUpdateParams {
    interface Raw {
        prompt?: serializers.AgentUpdateParamsPrompt.Raw | null;
        language?: serializers.AgentUpdateParamsLanguage.Raw | null;
        actions?: serializers.AgentUpdateParamsActions.Raw | null;
        voice?: serializers.AgentUpdateParamsVoice.Raw | null;
        initial_message?: serializers.AgentUpdateParamsInitialMessage.Raw | null;
        webhook?: serializers.AgentUpdateParamsWebhook.Raw | null;
        vector_database?: serializers.AgentUpdateParamsVectorDatabase.Raw | null;
        interrupt_sensitivity?: serializers.AgentUpdateParamsInterruptSensitivity.Raw | null;
        context_endpoint?: serializers.AgentUpdateParamsContextEndpoint.Raw | null;
        noise_suppression?: serializers.AgentUpdateParamsNoiseSuppression.Raw | null;
        endpointing_sensitivity?: serializers.AgentUpdateParamsEndpointingSensitivity.Raw | null;
    }
}
