/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AgentVoice: core.serialization.Schema<serializers.AgentVoice.Raw, Vocode.AgentVoice> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.lazyObject(async () => (await import("..")).AzureVoice),
        core.serialization.lazyObject(async () => (await import("..")).RimeVoice),
        core.serialization.lazyObject(async () => (await import("..")).ElevenLabsVoice),
    ]);

export declare namespace AgentVoice {
    type Raw = string | serializers.AzureVoice.Raw | serializers.RimeVoice.Raw | serializers.ElevenLabsVoice.Raw;
}
