/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AgentUpdateParamsActionsItemOne: core.serialization.Schema<
    serializers.AgentUpdateParamsActionsItemOne.Raw,
    Vocode.AgentUpdateParamsActionsItemOne
> = core.serialization
    .union("type", {
        action_transfer_call: core.serialization.lazyObject(
            async () => (await import("..")).TransferCallActionUpdateParams
        ),
        action_end_conversation: core.serialization.lazyObject(
            async () => (await import("..")).EndConversationActionUpdateParams
        ),
        action_dtmf: core.serialization.lazyObject(async () => (await import("..")).DtmfActionUpdateParams),
        action_add_to_conference: core.serialization.lazyObject(
            async () => (await import("..")).AddToConferenceActionUpdateParams
        ),
        action_set_hold: core.serialization.lazyObject(async () => (await import("..")).SetHoldActionUpdateParams),
        action_external: core.serialization.lazyObject(async () => (await import("..")).ExternalActionUpdateParams),
    })
    .transform<Vocode.AgentUpdateParamsActionsItemOne>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace AgentUpdateParamsActionsItemOne {
    type Raw =
        | AgentUpdateParamsActionsItemOne.ActionTransferCall
        | AgentUpdateParamsActionsItemOne.ActionEndConversation
        | AgentUpdateParamsActionsItemOne.ActionDtmf
        | AgentUpdateParamsActionsItemOne.ActionAddToConference
        | AgentUpdateParamsActionsItemOne.ActionSetHold
        | AgentUpdateParamsActionsItemOne.ActionExternal;

    interface ActionTransferCall extends serializers.TransferCallActionUpdateParams.Raw {
        type: "action_transfer_call";
    }

    interface ActionEndConversation extends serializers.EndConversationActionUpdateParams.Raw {
        type: "action_end_conversation";
    }

    interface ActionDtmf extends serializers.DtmfActionUpdateParams.Raw {
        type: "action_dtmf";
    }

    interface ActionAddToConference extends serializers.AddToConferenceActionUpdateParams.Raw {
        type: "action_add_to_conference";
    }

    interface ActionSetHold extends serializers.SetHoldActionUpdateParams.Raw {
        type: "action_set_hold";
    }

    interface ActionExternal extends serializers.ExternalActionUpdateParams.Raw {
        type: "action_external";
    }
}
