/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AgentUpdateParams: core.serialization.ObjectSchema<
    serializers.AgentUpdateParams.Raw,
    Vocode.AgentUpdateParams
> = core.serialization.object({
    prompt: core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsPrompt).optional(),
    language: core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsLanguage).optional(),
    actions: core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsActions).optional(),
    voice: core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsVoice).optional(),
    initialMessage: core.serialization.property(
        "initial_message",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsInitialMessage).optional()
    ),
    webhook: core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsWebhook).optional(),
    vectorDatabase: core.serialization.property(
        "vector_database",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsVectorDatabase).optional()
    ),
    interruptSensitivity: core.serialization.property(
        "interrupt_sensitivity",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsInterruptSensitivity).optional()
    ),
    contextEndpoint: core.serialization.property(
        "context_endpoint",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsContextEndpoint).optional()
    ),
    noiseSuppression: core.serialization.property(
        "noise_suppression",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsNoiseSuppression).optional()
    ),
    endpointingSensitivity: core.serialization.property(
        "endpointing_sensitivity",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsEndpointingSensitivity).optional()
    ),
    ivrNavigationMode: core.serialization.property(
        "ivr_navigation_mode",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsIvrNavigationMode).optional()
    ),
    conversationSpeed: core.serialization.property(
        "conversation_speed",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsConversationSpeed).optional()
    ),
    initialMessageDelay: core.serialization.property(
        "initial_message_delay",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsInitialMessageDelay).optional()
    ),
    openaiModelNameOverride: core.serialization.property(
        "openai_model_name_override",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsOpenaiModelNameOverride).optional()
    ),
    askIfHumanPresentOnIdle: core.serialization.property(
        "ask_if_human_present_on_idle",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsAskIfHumanPresentOnIdle).optional()
    ),
    openaiAccountConnection: core.serialization.property(
        "openai_account_connection",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsOpenaiAccountConnection).optional()
    ),
    runDoNotCallDetection: core.serialization.property(
        "run_do_not_call_detection",
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsRunDoNotCallDetection).optional()
    ),
});

export declare namespace AgentUpdateParams {
    interface Raw {
        prompt?: serializers.AgentUpdateParamsPrompt.Raw | null;
        language?: serializers.AgentUpdateParamsLanguage.Raw | null;
        actions?: serializers.AgentUpdateParamsActions.Raw | null;
        voice?: serializers.AgentUpdateParamsVoice.Raw | null;
        initial_message?: serializers.AgentUpdateParamsInitialMessage.Raw | null;
        webhook?: serializers.AgentUpdateParamsWebhook.Raw | null;
        vector_database?: serializers.AgentUpdateParamsVectorDatabase.Raw | null;
        interrupt_sensitivity?: serializers.AgentUpdateParamsInterruptSensitivity.Raw | null;
        context_endpoint?: serializers.AgentUpdateParamsContextEndpoint.Raw | null;
        noise_suppression?: serializers.AgentUpdateParamsNoiseSuppression.Raw | null;
        endpointing_sensitivity?: serializers.AgentUpdateParamsEndpointingSensitivity.Raw | null;
        ivr_navigation_mode?: serializers.AgentUpdateParamsIvrNavigationMode.Raw | null;
        conversation_speed?: serializers.AgentUpdateParamsConversationSpeed.Raw | null;
        initial_message_delay?: serializers.AgentUpdateParamsInitialMessageDelay.Raw | null;
        openai_model_name_override?: serializers.AgentUpdateParamsOpenaiModelNameOverride.Raw | null;
        ask_if_human_present_on_idle?: serializers.AgentUpdateParamsAskIfHumanPresentOnIdle.Raw | null;
        openai_account_connection?: serializers.AgentUpdateParamsOpenaiAccountConnection.Raw | null;
        run_do_not_call_detection?: serializers.AgentUpdateParamsRunDoNotCallDetection.Raw | null;
    }
}
