/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AgentUpdateParamsAskIfHumanPresentOnIdle: core.serialization.Schema<
    serializers.AgentUpdateParamsAskIfHumanPresentOnIdle.Raw,
    Vocode.AgentUpdateParamsAskIfHumanPresentOnIdle
> = core.serialization.undiscriminatedUnion([
    core.serialization.boolean(),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace AgentUpdateParamsAskIfHumanPresentOnIdle {
    type Raw = boolean | serializers.Undefined.Raw;
}
