/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AgentUpdateParamsActions: core.serialization.Schema<
    serializers.AgentUpdateParamsActions.Raw,
    Vocode.AgentUpdateParamsActions
> = core.serialization.undiscriminatedUnion([
    core.serialization.list(
        core.serialization.lazy(async () => (await import("..")).AgentUpdateParamsActionsAgentUpdateParamsActionsItem)
    ),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace AgentUpdateParamsActions {
    type Raw = serializers.AgentUpdateParamsActionsAgentUpdateParamsActionsItem.Raw[] | serializers.Undefined.Raw;
}
