/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Vocode from "../../api/index";
import * as core from "../../core";
import { Undefined } from "./Undefined";

export const AgentUpdateParamsIdleTimeSeconds: core.serialization.Schema<
    serializers.AgentUpdateParamsIdleTimeSeconds.Raw,
    Vocode.AgentUpdateParamsIdleTimeSeconds
> = core.serialization.undiscriminatedUnion([core.serialization.number(), Undefined]);

export declare namespace AgentUpdateParamsIdleTimeSeconds {
    type Raw = number | Undefined.Raw;
}
