/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AgentUpdateParamsIvrNavigationMode: core.serialization.Schema<
    serializers.AgentUpdateParamsIvrNavigationMode.Raw,
    Vocode.AgentUpdateParamsIvrNavigationMode
> = core.serialization.undiscriminatedUnion([
    core.serialization.stringLiteral("default"),
    core.serialization.stringLiteral("off"),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace AgentUpdateParamsIvrNavigationMode {
    type Raw = "default" | "off" | serializers.Undefined.Raw;
}
