/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AgentUpdateParamsEndpointingSensitivity: core.serialization.Schema<
    serializers.AgentUpdateParamsEndpointingSensitivity.Raw,
    Vocode.AgentUpdateParamsEndpointingSensitivity
> = core.serialization.enum_(["auto", "relaxed"]);

export declare namespace AgentUpdateParamsEndpointingSensitivity {
    type Raw = "auto" | "relaxed";
}
