/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const AgentUpdateParamsActionsAgentUpdateParamsActionsItem: core.serialization.Schema<
    serializers.AgentUpdateParamsActionsAgentUpdateParamsActionsItem.Raw,
    Vocode.AgentUpdateParamsActionsAgentUpdateParamsActionsItem
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("..")).EndConversationActionUpdateParams),
    core.serialization.lazyObject(async () => (await import("..")).DtmfActionUpdateParams),
]);

export declare namespace AgentUpdateParamsActionsAgentUpdateParamsActionsItem {
    type Raw = string | serializers.EndConversationActionUpdateParams.Raw | serializers.DtmfActionUpdateParams.Raw;
}
