/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const BuyPhoneNumberRequest: core.serialization.ObjectSchema<
    serializers.BuyPhoneNumberRequest.Raw,
    Vocode.BuyPhoneNumberRequest
> = core.serialization.object({
    areaCode: core.serialization.property("area_code", core.serialization.string().optional()),
    telephonyProvider: core.serialization.property(
        "telephony_provider",
        core.serialization.lazy(async () => (await import("..")).BuyPhoneNumberRequestTelephonyProvider).optional()
    ),
    telephonyAccountConnection: core.serialization.property(
        "telephony_account_connection",
        core.serialization.string().optional()
    ),
});

export declare namespace BuyPhoneNumberRequest {
    interface Raw {
        area_code?: string | null;
        telephony_provider?: serializers.BuyPhoneNumberRequestTelephonyProvider.Raw | null;
        telephony_account_connection?: string | null;
    }
}
