/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const BuyPhoneNumberRequestTelephonyProvider: core.serialization.Schema<
    serializers.BuyPhoneNumberRequestTelephonyProvider.Raw,
    Vocode.BuyPhoneNumberRequestTelephonyProvider
> = core.serialization.enum_(["vonage", "twilio"]);

export declare namespace BuyPhoneNumberRequestTelephonyProvider {
    type Raw = "vonage" | "twilio";
}
