/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const CallAgent: core.serialization.Schema<serializers.CallAgent.Raw, Vocode.CallAgent> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.lazyObject(async () => (await import("..")).Agent),
    ]);

export declare namespace CallAgent {
    type Raw = string | serializers.Agent.Raw;
}
