/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const CollectFieldFieldType: core.serialization.Schema<
    serializers.CollectFieldFieldType.Raw,
    Vocode.CollectFieldFieldType
> = core.serialization.enum_(["field_type_email", "field_type_address"]);

export declare namespace CollectFieldFieldType {
    type Raw = "field_type_email" | "field_type_address";
}
