/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const CreateActionRequest: core.serialization.Schema<
    serializers.CreateActionRequest.Raw,
    Vocode.CreateActionRequest
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).TransferCallActionParams),
    core.serialization.lazyObject(async () => (await import("..")).EndConversationActionParams),
    core.serialization.lazyObject(async () => (await import("..")).DtmfActionParams),
]);

export declare namespace CreateActionRequest {
    type Raw =
        | serializers.TransferCallActionParams.Raw
        | serializers.EndConversationActionParams.Raw
        | serializers.DtmfActionParams.Raw;
}
