/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const CreateCallAgentParamsPrompt: core.serialization.Schema<
    serializers.CreateCallAgentParamsPrompt.Raw,
    Vocode.CreateCallAgentParamsPrompt
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("..")).PromptParams),
]);

export declare namespace CreateCallAgentParamsPrompt {
    type Raw = string | serializers.PromptParams.Raw;
}
