/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const CreateCallAgentParamsWebhook: core.serialization.Schema<
    serializers.CreateCallAgentParamsWebhook.Raw,
    Vocode.CreateCallAgentParamsWebhook
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("..")).WebhookParams),
]);

export declare namespace CreateCallAgentParamsWebhook {
    type Raw = string | serializers.WebhookParams.Raw;
}
