/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const CreateCallAgentParamsOpenaiAccountConnection: core.serialization.Schema<
    serializers.CreateCallAgentParamsOpenaiAccountConnection.Raw,
    Vocode.CreateCallAgentParamsOpenaiAccountConnection
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).OpenAiAccountConnection),
    core.serialization.string(),
]);

export declare namespace CreateCallAgentParamsOpenaiAccountConnection {
    type Raw = serializers.OpenAiAccountConnection.Raw | string;
}
