/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const CreateCallRequestOnMachineAnswer: core.serialization.Schema<
    serializers.CreateCallRequestOnMachineAnswer.Raw,
    Vocode.CreateCallRequestOnMachineAnswer
> = core.serialization.enum_(["continue", "hangup"]);

export declare namespace CreateCallRequestOnMachineAnswer {
    type Raw = "continue" | "hangup";
}
