/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const CreateCallRequestAgent: core.serialization.Schema<
    serializers.CreateCallRequestAgent.Raw,
    Vocode.CreateCallRequestAgent
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("..")).CreateCallAgentParams),
]);

export declare namespace CreateCallRequestAgent {
    type Raw = string | serializers.CreateCallAgentParams.Raw;
}
