/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const DtmfActionParams: core.serialization.ObjectSchema<
    serializers.DtmfActionParams.Raw,
    Vocode.DtmfActionParams
> = core.serialization.object({
    config: core.serialization.lazyObject(async () => (await import("..")).EmptyActionConfig).optional(),
});

export declare namespace DtmfActionParams {
    interface Raw {
        config?: serializers.EmptyActionConfig.Raw | null;
    }
}
