/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const DtmfAction: core.serialization.ObjectSchema<serializers.DtmfAction.Raw, Vocode.DtmfAction> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        type: core.serialization.lazy(async () => (await import("..")).ActionType).optional(),
        config: core.serialization.lazyObject(async () => (await import("..")).ActionConfig).optional(),
    });

export declare namespace DtmfAction {
    interface Raw {
        id: string;
        user_id: string;
        type?: serializers.ActionType.Raw | null;
        config?: serializers.ActionConfig.Raw | null;
    }
}
