/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const DtmfActionUpdateParamsActionTrigger: core.serialization.Schema<
    serializers.DtmfActionUpdateParamsActionTrigger.Raw,
    Vocode.DtmfActionUpdateParamsActionTrigger
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazy(async () => (await import("..")).DtmfActionUpdateParamsActionTriggerZero),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace DtmfActionUpdateParamsActionTrigger {
    type Raw = serializers.DtmfActionUpdateParamsActionTriggerZero.Raw | serializers.Undefined.Raw;
}
