/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const ElevenLabsVoiceUpdateParamsModelId: core.serialization.Schema<
    serializers.ElevenLabsVoiceUpdateParamsModelId.Raw,
    Vocode.ElevenLabsVoiceUpdateParamsModelId
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace ElevenLabsVoiceUpdateParamsModelId {
    type Raw = string | serializers.Undefined.Raw;
}
