/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const EndConversationActionUpdateParams: core.serialization.ObjectSchema<
    serializers.EndConversationActionUpdateParams.Raw,
    Vocode.EndConversationActionUpdateParams
> = core.serialization.object({
    config: core.serialization
        .lazy(async () => (await import("..")).EndConversationActionUpdateParamsConfig)
        .optional(),
});

export declare namespace EndConversationActionUpdateParams {
    interface Raw {
        config?: serializers.EndConversationActionUpdateParamsConfig.Raw | null;
    }
}
