/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const EndConversationActionUpdateParamsActionTriggerZero: core.serialization.Schema<
    serializers.EndConversationActionUpdateParamsActionTriggerZero.Raw,
    Vocode.EndConversationActionUpdateParamsActionTriggerZero
> = core.serialization
    .union("type", {
        action_trigger_function_call: core.serialization.lazyObject(
            async () => (await import("..")).FunctionCallActionTrigger
        ),
        action_trigger_phrase_based: core.serialization.lazyObject(
            async () => (await import("..")).PhraseBasedActionTrigger
        ),
    })
    .transform<Vocode.EndConversationActionUpdateParamsActionTriggerZero>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace EndConversationActionUpdateParamsActionTriggerZero {
    type Raw =
        | EndConversationActionUpdateParamsActionTriggerZero.ActionTriggerFunctionCall
        | EndConversationActionUpdateParamsActionTriggerZero.ActionTriggerPhraseBased;

    interface ActionTriggerFunctionCall extends serializers.FunctionCallActionTrigger.Raw {
        type: "action_trigger_function_call";
    }

    interface ActionTriggerPhraseBased extends serializers.PhraseBasedActionTrigger.Raw {
        type: "action_trigger_phrase_based";
    }
}
