/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const EndConversationActionUpdateParamsConfig: core.serialization.Schema<
    serializers.EndConversationActionUpdateParamsConfig.Raw,
    Vocode.EndConversationActionUpdateParamsConfig
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).EmptyActionConfig),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace EndConversationActionUpdateParamsConfig {
    type Raw = serializers.EmptyActionConfig.Raw | serializers.Undefined.Raw;
}
