/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const EndConversationAction: core.serialization.ObjectSchema<
    serializers.EndConversationAction.Raw,
    Vocode.EndConversationAction
> = core.serialization.object({
    id: core.serialization.string(),
    userId: core.serialization.property("user_id", core.serialization.string()),
    config: core.serialization.lazyObject(async () => (await import("..")).EmptyActionConfig).optional(),
    actionTrigger: core.serialization.property(
        "action_trigger",
        core.serialization.lazy(async () => (await import("..")).EndConversationActionActionTrigger).optional()
    ),
});

export declare namespace EndConversationAction {
    interface Raw {
        id: string;
        user_id: string;
        config?: serializers.EmptyActionConfig.Raw | null;
        action_trigger?: serializers.EndConversationActionActionTrigger.Raw | null;
    }
}
