/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const ExternalActionParams: core.serialization.ObjectSchema<
    serializers.ExternalActionParams.Raw,
    Vocode.ExternalActionParams
> = core.serialization.object({
    config: core.serialization.lazyObject(async () => (await import("..")).ExternalActionConfig),
    actionTrigger: core.serialization.property(
        "action_trigger",
        core.serialization.lazy(async () => (await import("..")).ExternalActionParamsActionTrigger).optional()
    ),
});

export declare namespace ExternalActionParams {
    interface Raw {
        config: serializers.ExternalActionConfig.Raw;
        action_trigger?: serializers.ExternalActionParamsActionTrigger.Raw | null;
    }
}
