/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const ExternalActionUpdateParamsConfig: core.serialization.Schema<
    serializers.ExternalActionUpdateParamsConfig.Raw,
    Vocode.ExternalActionUpdateParamsConfig
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazyObject(async () => (await import("..")).ExternalActionConfig),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace ExternalActionUpdateParamsConfig {
    type Raw = serializers.ExternalActionConfig.Raw | serializers.Undefined.Raw;
}
