/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const FunctionCallActionTrigger: core.serialization.ObjectSchema<
    serializers.FunctionCallActionTrigger.Raw,
    Vocode.FunctionCallActionTrigger
> = core.serialization.object({
    config: core.serialization.lazyObject(async () => (await import("..")).FunctionCallActionTriggerConfig).optional(),
});

export declare namespace FunctionCallActionTrigger {
    interface Raw {
        config?: serializers.FunctionCallActionTriggerConfig.Raw | null;
    }
}
