/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const GetVoiceResponse: core.serialization.Schema<serializers.GetVoiceResponse.Raw, Vocode.GetVoiceResponse> =
    core.serialization.undiscriminatedUnion([
        core.serialization.lazyObject(async () => (await import("..")).AzureVoice),
        core.serialization.lazyObject(async () => (await import("..")).RimeVoice),
        core.serialization.lazyObject(async () => (await import("..")).ElevenLabsVoice),
    ]);

export declare namespace GetVoiceResponse {
    type Raw = serializers.AzureVoice.Raw | serializers.RimeVoice.Raw | serializers.ElevenLabsVoice.Raw;
}
