/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const NormalizedAgentEndpointingSensitivity: core.serialization.Schema<
    serializers.NormalizedAgentEndpointingSensitivity.Raw,
    Vocode.NormalizedAgentEndpointingSensitivity
> = core.serialization.enum_(["auto", "relaxed", "sensitive"]);

export declare namespace NormalizedAgentEndpointingSensitivity {
    type Raw = "auto" | "relaxed" | "sensitive";
}
