/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const NormalizedCallOnNoHumanAnswer: core.serialization.Schema<
    serializers.NormalizedCallOnNoHumanAnswer.Raw,
    Vocode.NormalizedCallOnNoHumanAnswer
> = core.serialization.enum_(["continue", "hangup"]);

export declare namespace NormalizedCallOnNoHumanAnswer {
    type Raw = "continue" | "hangup";
}
