/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const NormalizedPhoneNumberTelephonyAccountConnection: core.serialization.Schema<
    serializers.NormalizedPhoneNumberTelephonyAccountConnection.Raw,
    Vocode.NormalizedPhoneNumberTelephonyAccountConnection
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("..")).TwilioAccountConnection),
]);

export declare namespace NormalizedPhoneNumberTelephonyAccountConnection {
    type Raw = string | serializers.TwilioAccountConnection.Raw;
}
