/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const NormalizedPhoneNumber: core.serialization.ObjectSchema<
    serializers.NormalizedPhoneNumber.Raw,
    Vocode.NormalizedPhoneNumber
> = core.serialization.object({
    id: core.serialization.string(),
    userId: core.serialization.property("user_id", core.serialization.string()),
    active: core.serialization.boolean().optional(),
    label: core.serialization.string().optional(),
    inboundAgent: core.serialization.property("inbound_agent", core.serialization.string()),
    outboundOnly: core.serialization.property("outbound_only", core.serialization.boolean().optional()),
    number: core.serialization.string(),
});

export declare namespace NormalizedPhoneNumber {
    interface Raw {
        id: string;
        user_id: string;
        active?: boolean | null;
        label?: string | null;
        inbound_agent: string;
        outbound_only?: boolean | null;
        number: string;
    }
}
