/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const NormalizedPhoneNumberTelephonyProvider: core.serialization.Schema<
    serializers.NormalizedPhoneNumberTelephonyProvider.Raw,
    Vocode.NormalizedPhoneNumberTelephonyProvider
> = core.serialization.enum_(["vonage", "twilio"]);

export declare namespace NormalizedPhoneNumberTelephonyProvider {
    type Raw = "vonage" | "twilio";
}
