/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const NormalizedCallStage: core.serialization.Schema<
    serializers.NormalizedCallStage.Raw,
    Vocode.NormalizedCallStage
> = core.serialization.enum_(["created", "picked_up", "transfer_started", "transfer_successful"]);

export declare namespace NormalizedCallStage {
    type Raw = "created" | "picked_up" | "transfer_started" | "transfer_successful";
}
