/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const Page: core.serialization.ObjectSchema<serializers.Page.Raw, Vocode.Page> = core.serialization.object({
    items: core.serialization.list(core.serialization.unknown()),
    page: core.serialization.number(),
    size: core.serialization.number(),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
});

export declare namespace Page {
    interface Raw {
        items: unknown[];
        page: number;
        size: number;
        has_more: boolean;
    }
}
