/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PhoneNumberPage: core.serialization.ObjectSchema<serializers.PhoneNumberPage.Raw, Vocode.PhoneNumberPage> =
    core.serialization.object({
        items: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("..")).NormalizedPhoneNumber)
        ),
        page: core.serialization.number(),
        size: core.serialization.number(),
        hasMore: core.serialization.property("has_more", core.serialization.boolean()),
        total: core.serialization.number(),
        totalIsEstimated: core.serialization.property("total_is_estimated", core.serialization.boolean()),
    });

export declare namespace PhoneNumberPage {
    interface Raw {
        items: serializers.NormalizedPhoneNumber.Raw[];
        page: number;
        size: number;
        has_more: boolean;
        total: number;
        total_is_estimated: boolean;
    }
}
