/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PhoneNumberTelephonyProvider: core.serialization.Schema<
    serializers.PhoneNumberTelephonyProvider.Raw,
    Vocode.PhoneNumberTelephonyProvider
> = core.serialization.enum_(["vonage", "twilio"]);

export declare namespace PhoneNumberTelephonyProvider {
    type Raw = "vonage" | "twilio";
}
