/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PhoneNumber: core.serialization.ObjectSchema<serializers.PhoneNumber.Raw, Vocode.PhoneNumber> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        active: core.serialization.boolean().optional(),
        inboundAgent: core.serialization.property(
            "inbound_agent",
            core.serialization.lazyObject(async () => (await import("..")).Agent)
        ),
        number: core.serialization.string(),
    });

export declare namespace PhoneNumber {
    interface Raw {
        id: string;
        user_id: string;
        active?: boolean | null;
        inbound_agent: serializers.Agent.Raw;
        number: string;
    }
}
