/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PhraseTrigger: core.serialization.ObjectSchema<serializers.PhraseTrigger.Raw, Vocode.PhraseTrigger> =
    core.serialization.object({
        phrase: core.serialization.string(),
        conditions: core.serialization.list(core.serialization.stringLiteral("phrase_condition_type_contains")),
    });

export declare namespace PhraseTrigger {
    interface Raw {
        phrase: string;
        conditions: "phrase_condition_type_contains"[];
    }
}
