/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PhraseBasedActionTriggerConfig: core.serialization.ObjectSchema<
    serializers.PhraseBasedActionTriggerConfig.Raw,
    Vocode.PhraseBasedActionTriggerConfig
> = core.serialization.object({
    phraseTriggers: core.serialization.property(
        "phrase_triggers",
        core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).PhraseTrigger))
    ),
});

export declare namespace PhraseBasedActionTriggerConfig {
    interface Raw {
        phrase_triggers: serializers.PhraseTrigger.Raw[];
    }
}
