/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PineconeVectorDatabaseParams: core.serialization.ObjectSchema<
    serializers.PineconeVectorDatabaseParams.Raw,
    Vocode.PineconeVectorDatabaseParams
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).VectorDatabaseType),
    index: core.serialization.string(),
    apiKey: core.serialization.property("api_key", core.serialization.string()),
    apiEnvironment: core.serialization.property("api_environment", core.serialization.string()),
});

export declare namespace PineconeVectorDatabaseParams {
    interface Raw {
        type: serializers.VectorDatabaseType.Raw;
        index: string;
        api_key: string;
        api_environment: string;
    }
}
