/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PineconeVectorDatabaseUpdateParamsApiEnvironment: core.serialization.Schema<
    serializers.PineconeVectorDatabaseUpdateParamsApiEnvironment.Raw,
    Vocode.PineconeVectorDatabaseUpdateParamsApiEnvironment
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace PineconeVectorDatabaseUpdateParamsApiEnvironment {
    type Raw = string | serializers.Undefined.Raw;
}
