/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PlanType: core.serialization.Schema<serializers.PlanType.Raw, Vocode.PlanType> = core.serialization.enum_([
    "free",
    "developer",
    "enterprise",
]);

export declare namespace PlanType {
    type Raw = "free" | "developer" | "enterprise";
}
