/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PlayHtVoiceParams: core.serialization.ObjectSchema<
    serializers.PlayHtVoiceParams.Raw,
    Vocode.PlayHtVoiceParams
> = core.serialization.object({
    voiceId: core.serialization.property("voice_id", core.serialization.string()),
    apiUserId: core.serialization.property("api_user_id", core.serialization.string().optional()),
    apiKey: core.serialization.property("api_key", core.serialization.string().optional()),
    version: core.serialization.lazy(async () => (await import("..")).PlayHtVoiceParamsVersion).optional(),
    speed: core.serialization.number().optional(),
    quality: core.serialization.lazy(async () => (await import("..")).PlayHtVoiceParamsQuality).optional(),
    temperature: core.serialization.number().optional(),
    topP: core.serialization.property("top_p", core.serialization.number().optional()),
    textGuidance: core.serialization.property("text_guidance", core.serialization.number().optional()),
    voiceGuidance: core.serialization.property("voice_guidance", core.serialization.number().optional()),
    experimentalRemoveSilence: core.serialization.property(
        "experimental_remove_silence",
        core.serialization.boolean().optional()
    ),
});

export declare namespace PlayHtVoiceParams {
    interface Raw {
        voice_id: string;
        api_user_id?: string | null;
        api_key?: string | null;
        version?: serializers.PlayHtVoiceParamsVersion.Raw | null;
        speed?: number | null;
        quality?: serializers.PlayHtVoiceParamsQuality.Raw | null;
        temperature?: number | null;
        top_p?: number | null;
        text_guidance?: number | null;
        voice_guidance?: number | null;
        experimental_remove_silence?: boolean | null;
    }
}
