/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PlayHtVoiceParams: core.serialization.ObjectSchema<
    serializers.PlayHtVoiceParams.Raw,
    Vocode.PlayHtVoiceParams
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).VoiceType),
    voiceId: core.serialization.property("voice_id", core.serialization.string()),
    apiUserId: core.serialization.property("api_user_id", core.serialization.string()),
    apiKey: core.serialization.property("api_key", core.serialization.string()),
});

export declare namespace PlayHtVoiceParams {
    interface Raw {
        type: serializers.VoiceType.Raw;
        voice_id: string;
        api_user_id: string;
        api_key: string;
    }
}
