/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PlayHtVoiceVersion: core.serialization.Schema<
    serializers.PlayHtVoiceVersion.Raw,
    Vocode.PlayHtVoiceVersion
> = core.serialization.enum_(["1", "2"]);

export declare namespace PlayHtVoiceVersion {
    type Raw = "1" | "2";
}
