/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PlayHtVoiceUpdateParamsVersion: core.serialization.Schema<
    serializers.PlayHtVoiceUpdateParamsVersion.Raw,
    Vocode.PlayHtVoiceUpdateParamsVersion
> = core.serialization.undiscriminatedUnion([
    core.serialization.stringLiteral("1"),
    core.serialization.stringLiteral("2"),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace PlayHtVoiceUpdateParamsVersion {
    type Raw = "1" | "2" | serializers.Undefined.Raw;
}
