/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PlayHtVoice: core.serialization.ObjectSchema<serializers.PlayHtVoice.Raw, Vocode.PlayHtVoice> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        voiceId: core.serialization.property("voice_id", core.serialization.string()),
        apiUserId: core.serialization.property("api_user_id", core.serialization.string().optional()),
        apiKey: core.serialization.property("api_key", core.serialization.string().optional()),
        version: core.serialization.lazy(async () => (await import("..")).PlayHtVoiceVersion).optional(),
    });

export declare namespace PlayHtVoice {
    interface Raw {
        id: string;
        user_id: string;
        voice_id: string;
        api_user_id?: string | null;
        api_key?: string | null;
        version?: serializers.PlayHtVoiceVersion.Raw | null;
    }
}
