/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PlayHtVoiceUpdateParamsQuality: core.serialization.Schema<
    serializers.PlayHtVoiceUpdateParamsQuality.Raw,
    Vocode.PlayHtVoiceUpdateParamsQuality
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazy(async () => (await import("..")).PlayHtVoiceUpdateParamsQuality),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace PlayHtVoiceUpdateParamsQuality {
    type Raw = serializers.PlayHtVoiceUpdateParamsQuality.Raw | serializers.Undefined.Raw;
}
