/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PlayHtVoiceParams: core.serialization.ObjectSchema<
    serializers.PlayHtVoiceParams.Raw,
    Vocode.PlayHtVoiceParams
> = core.serialization.object({
    voiceId: core.serialization.property("voice_id", core.serialization.string()),
    apiUserId: core.serialization.property("api_user_id", core.serialization.string().optional()),
    apiKey: core.serialization.property("api_key", core.serialization.string().optional()),
    version: core.serialization.lazy(async () => (await import("..")).PlayHtVoiceParamsVersion).optional(),
});

export declare namespace PlayHtVoiceParams {
    interface Raw {
        voice_id: string;
        api_user_id?: string | null;
        api_key?: string | null;
        version?: serializers.PlayHtVoiceParamsVersion.Raw | null;
    }
}
