/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PlayHtVoiceUpdateParamsTemperature: core.serialization.Schema<
    serializers.PlayHtVoiceUpdateParamsTemperature.Raw,
    Vocode.PlayHtVoiceUpdateParamsTemperature
> = core.serialization.undiscriminatedUnion([
    core.serialization.number(),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace PlayHtVoiceUpdateParamsTemperature {
    type Raw = number | serializers.Undefined.Raw;
}
