/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PromptUpdateParamsCollectFields: core.serialization.Schema<
    serializers.PromptUpdateParamsCollectFields.Raw,
    Vocode.PromptUpdateParamsCollectFields
> = core.serialization.undiscriminatedUnion([
    core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).CollectField)),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace PromptUpdateParamsCollectFields {
    type Raw = serializers.CollectField.Raw[] | serializers.Undefined.Raw;
}
