/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PromptParams: core.serialization.ObjectSchema<serializers.PromptParams.Raw, Vocode.PromptParams> =
    core.serialization.object({
        content: core.serialization.string(),
        collectFields: core.serialization.property(
            "collect_fields",
            core.serialization
                .list(core.serialization.lazyObject(async () => (await import("..")).CollectField))
                .optional()
        ),
        contextEndpoint: core.serialization.property("context_endpoint", core.serialization.string().optional()),
    });

export declare namespace PromptParams {
    interface Raw {
        content: string;
        collect_fields?: serializers.CollectField.Raw[] | null;
        context_endpoint?: string | null;
    }
}
