/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PromptParamsPromptTemplate: core.serialization.Schema<
    serializers.PromptParamsPromptTemplate.Raw,
    Vocode.PromptParamsPromptTemplate
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("..")).PromptTemplate),
]);

export declare namespace PromptParamsPromptTemplate {
    type Raw = string | serializers.PromptTemplate.Raw;
}
