/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PromptUpdateParamsPromptTemplate: core.serialization.Schema<
    serializers.PromptUpdateParamsPromptTemplate.Raw,
    Vocode.PromptUpdateParamsPromptTemplate
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.lazyObject(async () => (await import("..")).PromptTemplate),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace PromptUpdateParamsPromptTemplate {
    type Raw = string | serializers.PromptTemplate.Raw | serializers.Undefined.Raw;
}
