/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PromptPage: core.serialization.ObjectSchema<serializers.PromptPage.Raw, Vocode.PromptPage> =
    core.serialization.object({
        items: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("..")).NormalizedPrompt)
        ),
        page: core.serialization.number(),
        size: core.serialization.number(),
        hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    });

export declare namespace PromptPage {
    interface Raw {
        items: serializers.NormalizedPrompt.Raw[];
        page: number;
        size: number;
        has_more: boolean;
    }
}
