/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const PromptUpdateParams: core.serialization.ObjectSchema<
    serializers.PromptUpdateParams.Raw,
    Vocode.PromptUpdateParams
> = core.serialization.object({
    content: core.serialization.lazy(async () => (await import("..")).PromptUpdateParamsContent).optional(),
    collectFields: core.serialization.property(
        "collect_fields",
        core.serialization.lazy(async () => (await import("..")).PromptUpdateParamsCollectFields).optional()
    ),
    contextEndpoint: core.serialization.property(
        "context_endpoint",
        core.serialization.lazy(async () => (await import("..")).PromptUpdateParamsContextEndpoint).optional()
    ),
});

export declare namespace PromptUpdateParams {
    interface Raw {
        content?: serializers.PromptUpdateParamsContent.Raw | null;
        collect_fields?: serializers.PromptUpdateParamsCollectFields.Raw | null;
        context_endpoint?: serializers.PromptUpdateParamsContextEndpoint.Raw | null;
    }
}
