/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const RimeVoiceUpdateParams: core.serialization.ObjectSchema<
    serializers.RimeVoiceUpdateParams.Raw,
    Vocode.RimeVoiceUpdateParams
> = core.serialization.object({
    speaker: core.serialization.lazy(async () => (await import("..")).RimeVoiceUpdateParamsSpeaker).optional(),
    speedAlpha: core.serialization.property(
        "speed_alpha",
        core.serialization.lazy(async () => (await import("..")).RimeVoiceUpdateParamsSpeedAlpha).optional()
    ),
    modelId: core.serialization.property(
        "model_id",
        core.serialization.lazy(async () => (await import("..")).RimeVoiceUpdateParamsModelId).optional()
    ),
});

export declare namespace RimeVoiceUpdateParams {
    interface Raw {
        speaker?: serializers.RimeVoiceUpdateParamsSpeaker.Raw | null;
        speed_alpha?: serializers.RimeVoiceUpdateParamsSpeedAlpha.Raw | null;
        model_id?: serializers.RimeVoiceUpdateParamsModelId.Raw | null;
    }
}
