/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const RimeVoiceUpdateParams: core.serialization.ObjectSchema<
    serializers.RimeVoiceUpdateParams.Raw,
    Vocode.RimeVoiceUpdateParams
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("..")).VoiceType),
    speaker: core.serialization.lazy(async () => (await import("..")).RimeVoiceUpdateParamsSpeaker).optional(),
});

export declare namespace RimeVoiceUpdateParams {
    interface Raw {
        type: serializers.VoiceType.Raw;
        speaker?: serializers.RimeVoiceUpdateParamsSpeaker.Raw | null;
    }
}
