/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const RimeVoice: core.serialization.ObjectSchema<serializers.RimeVoice.Raw, Vocode.RimeVoice> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        type: core.serialization.lazy(async () => (await import("..")).VoiceType).optional(),
        speaker: core.serialization.string(),
    });

export declare namespace RimeVoice {
    interface Raw {
        id: string;
        user_id: string;
        type?: serializers.VoiceType.Raw | null;
        speaker: string;
    }
}
