/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const RimeVoiceModelId: core.serialization.Schema<serializers.RimeVoiceModelId.Raw, Vocode.RimeVoiceModelId> =
    core.serialization.undiscriminatedUnion([
        core.serialization.stringLiteral("mist"),
        core.serialization.stringLiteral("v1"),
        core.serialization.lazyObject(async () => (await import("..")).Undefined),
    ]);

export declare namespace RimeVoiceModelId {
    type Raw = "mist" | "v1" | serializers.Undefined.Raw;
}
