/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const RimeVoiceParams: core.serialization.ObjectSchema<serializers.RimeVoiceParams.Raw, Vocode.RimeVoiceParams> =
    core.serialization.object({
        type: core.serialization.lazy(async () => (await import("..")).VoiceType),
        speaker: core.serialization.string(),
    });

export declare namespace RimeVoiceParams {
    interface Raw {
        type: serializers.VoiceType.Raw;
        speaker: string;
    }
}
