/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const RimeVoiceParams: core.serialization.ObjectSchema<serializers.RimeVoiceParams.Raw, Vocode.RimeVoiceParams> =
    core.serialization.object({
        speaker: core.serialization.string(),
        speedAlpha: core.serialization.property("speed_alpha", core.serialization.number().optional()),
    });

export declare namespace RimeVoiceParams {
    interface Raw {
        speaker: string;
        speed_alpha?: number | null;
    }
}
