/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const SetHoldActionUpdateParams: core.serialization.ObjectSchema<
    serializers.SetHoldActionUpdateParams.Raw,
    Vocode.SetHoldActionUpdateParams
> = core.serialization.object({
    config: core.serialization.lazy(async () => (await import("..")).SetHoldActionUpdateParamsConfig).optional(),
    actionTrigger: core.serialization.property(
        "action_trigger",
        core.serialization.lazy(async () => (await import("..")).SetHoldActionUpdateParamsActionTrigger).optional()
    ),
});

export declare namespace SetHoldActionUpdateParams {
    interface Raw {
        config?: serializers.SetHoldActionUpdateParamsConfig.Raw | null;
        action_trigger?: serializers.SetHoldActionUpdateParamsActionTrigger.Raw | null;
    }
}
