/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const SetHoldAction: core.serialization.ObjectSchema<serializers.SetHoldAction.Raw, Vocode.SetHoldAction> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        config: core.serialization.lazyObject(async () => (await import("..")).EmptyActionConfig).optional(),
        actionTrigger: core.serialization.property(
            "action_trigger",
            core.serialization.lazy(async () => (await import("..")).SetHoldActionActionTrigger).optional()
        ),
    });

export declare namespace SetHoldAction {
    interface Raw {
        id: string;
        user_id: string;
        config?: serializers.EmptyActionConfig.Raw | null;
        action_trigger?: serializers.SetHoldActionActionTrigger.Raw | null;
    }
}
