/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const TransferCallActionUpdateParams: core.serialization.ObjectSchema<
    serializers.TransferCallActionUpdateParams.Raw,
    Vocode.TransferCallActionUpdateParams
> = core.serialization.object({
    config: core.serialization.lazy(async () => (await import("..")).TransferCallActionUpdateParamsConfig).optional(),
});

export declare namespace TransferCallActionUpdateParams {
    interface Raw {
        config?: serializers.TransferCallActionUpdateParamsConfig.Raw | null;
    }
}
