/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const TransferCallAction: core.serialization.ObjectSchema<
    serializers.TransferCallAction.Raw,
    Vocode.TransferCallAction
> = core.serialization.object({
    id: core.serialization.string(),
    userId: core.serialization.property("user_id", core.serialization.string()),
    config: core.serialization.lazyObject(async () => (await import("..")).TransferCallConfig),
    actionTrigger: core.serialization.property(
        "action_trigger",
        core.serialization.lazy(async () => (await import("..")).TransferCallActionActionTrigger).optional()
    ),
});

export declare namespace TransferCallAction {
    interface Raw {
        id: string;
        user_id: string;
        config: serializers.TransferCallConfig.Raw;
        action_trigger?: serializers.TransferCallActionActionTrigger.Raw | null;
    }
}
