/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const TransferCallActionUpdateParamsActionTrigger: core.serialization.Schema<
    serializers.TransferCallActionUpdateParamsActionTrigger.Raw,
    Vocode.TransferCallActionUpdateParamsActionTrigger
> = core.serialization.undiscriminatedUnion([
    core.serialization.lazy(async () => (await import("..")).TransferCallActionUpdateParamsActionTriggerZero),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace TransferCallActionUpdateParamsActionTrigger {
    type Raw = serializers.TransferCallActionUpdateParamsActionTriggerZero.Raw | serializers.Undefined.Raw;
}
