/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const Undefined: core.serialization.ObjectSchema<serializers.Undefined.Raw, Vocode.Undefined> =
    core.serialization.object({});

export declare namespace Undefined {
    interface Raw {}
}
