/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const VectorDatabasePage: core.serialization.ObjectSchema<
    serializers.VectorDatabasePage.Raw,
    Vocode.VectorDatabasePage
> = core.serialization.object({
    items: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("..")).PineconeVectorDatabase)
    ),
    page: core.serialization.number(),
    size: core.serialization.number(),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
});

export declare namespace VectorDatabasePage {
    interface Raw {
        items: serializers.PineconeVectorDatabase.Raw[];
        page: number;
        size: number;
        has_more: boolean;
    }
}
