/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const Webhook: core.serialization.ObjectSchema<serializers.Webhook.Raw, Vocode.Webhook> =
    core.serialization.object({
        id: core.serialization.string(),
        userId: core.serialization.property("user_id", core.serialization.string()),
        subscriptions: core.serialization.list(core.serialization.lazy(async () => (await import("..")).EventType)),
        url: core.serialization.string(),
        method: core.serialization.lazy(async () => (await import("..")).HttpMethod).optional(),
    });

export declare namespace Webhook {
    interface Raw {
        id: string;
        user_id: string;
        subscriptions: serializers.EventType.Raw[];
        url: string;
        method?: serializers.HttpMethod.Raw | null;
    }
}
