/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const WebhookParams: core.serialization.ObjectSchema<serializers.WebhookParams.Raw, Vocode.WebhookParams> =
    core.serialization.object({
        subscriptions: core.serialization.list(core.serialization.lazy(async () => (await import("..")).EventType)),
        url: core.serialization.string(),
        method: core.serialization.lazy(async () => (await import("..")).HttpMethod).optional(),
    });

export declare namespace WebhookParams {
    interface Raw {
        subscriptions: serializers.EventType.Raw[];
        url: string;
        method?: serializers.HttpMethod.Raw | null;
    }
}
