/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Vocode from "../../api";
import * as core from "../../core";

export const WebhookUpdateParamsSubscriptions: core.serialization.Schema<
    serializers.WebhookUpdateParamsSubscriptions.Raw,
    Vocode.WebhookUpdateParamsSubscriptions
> = core.serialization.undiscriminatedUnion([
    core.serialization.list(core.serialization.lazy(async () => (await import("..")).EventType)),
    core.serialization.lazyObject(async () => (await import("..")).Undefined),
]);

export declare namespace WebhookUpdateParamsSubscriptions {
    type Raw = serializers.EventType.Raw[] | serializers.Undefined.Raw;
}
