/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Vocode from "../../../../../api";
import * as core from "../../../../../core";

export const AddToSteeringPoolRequest: core.serialization.Schema<
    serializers.AddToSteeringPoolRequest.Raw,
    Omit<Vocode.AddToSteeringPoolRequest, "id">
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", core.serialization.string().optional()),
});

export declare namespace AddToSteeringPoolRequest {
    interface Raw {
        phone_number?: string | null;
    }
}
