/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Vocode from "../../../../../api";
import * as core from "../../../../../core";

export const RemoveFromSteeringPoolRequest: core.serialization.Schema<
    serializers.RemoveFromSteeringPoolRequest.Raw,
    Omit<Vocode.RemoveFromSteeringPoolRequest, "id">
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", core.serialization.string()),
});

export declare namespace RemoveFromSteeringPoolRequest {
    interface Raw {
        phone_number: string;
    }
}
