/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vocode from "../../../..";

export interface CreateCallRequest {
    fromNumber: string;
    toNumber: string;
    agent: Vocode.CreateCallRequestAgent;
    onMachineAnswer?: Vocode.CreateCallRequestOnMachineAnswer;
}
