/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const VocodeEnvironment = {
    Production: "https://api.vocode.dev",
    Staging: "https://vocode-api-staging-5xerktxr4q-uc.a.run.app",
} as const;

export type VocodeEnvironment = typeof VocodeEnvironment.Production | typeof VocodeEnvironment.Staging;
