/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Vocode from "../../../../../api";
import * as core from "../../../../../core";

export const BuyPhoneNumberRequest: core.serialization.Schema<
    serializers.BuyPhoneNumberRequest.Raw,
    Vocode.BuyPhoneNumberRequest
> = core.serialization.object({
    areaCode: core.serialization.property("area_code", core.serialization.string().optional()),
});

export declare namespace BuyPhoneNumberRequest {
    interface Raw {
        area_code?: string | null;
    }
}
