/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Vocode from "../../../../../api";
import * as core from "../../../../../core";

export const LinkPhoneNumberRequest: core.serialization.Schema<
    serializers.LinkPhoneNumberRequest.Raw,
    Vocode.LinkPhoneNumberRequest
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", core.serialization.string()),
    telephonyAccountConnection: core.serialization.property(
        "telephony_account_connection",
        core.serialization.string()
    ),
    outboundOnly: core.serialization.property("outbound_only", core.serialization.boolean().optional()),
});

export declare namespace LinkPhoneNumberRequest {
    interface Raw {
        phone_number: string;
        telephony_account_connection: string;
        outbound_only?: boolean | null;
    }
}
